### ISSUE TITLE
New device won't connect to mocktuyacloud

### ISSUE THREAD

**Issue by sheppy99** [kueblc/mocktuyacloud#6]
I've got a new WiFi switch that I'd like to change to Tasmota. I've tried tuya-convert and the device connects but doesn't seem to transfer anything so after a reboot I tried mocktuyacloud. After a fight with Node and its dependencies I've managed to get it to run and I can see a secure network tuya_mdev_test on my phone, but the WiFi switch doesn't seem to connect to it. The command window of mocktuyacloud keeps cycling these messages

`MockTuyaCloud: prompting unlinked devices to connect to network
TuyaLink: Sending Smartlink initilization packets
TuyaLink: Sending SmartLink data packets
TuyaLink: Finished sending packets.
`
The WiFi LED on the switch is flashing quickly, and the buttons turn the relays on and off. Pressing and holding the first button on the switch stops the flashing and it can be persuaded to slowly flash, or go out but it doesn't seem to interact with mocktuyacloud 

I can connect my phone to the AP using the key in ota-firmware.sh and I can send and receive mqtt messages to the default gateway the AP gives out.
Am I missing a step? How does the WiFi switch know the SSID "tuya_mdev_test" and its password? I'm happy to use my switch to work out whats needed

**Comment by kueblc** [comment]
Hi @sheppy99 thanks for your report.

I see that you've found your way over to `tuya-convert` which is now the recommended way to do firmware flashing. It uses the same principle but is much better documented and designed specifically for firmware flashing, while `MockTuyaCloud` has a broader scope and is oriented toward developers.

To answer your question, the device gets the WiFi credentials through the smart config process, which seemed to be failing for you in this case. It may be because it needed another device connected to do broadcast, or simply that `tuya-convert`'s smart config is more robust in timing and this framework hasn't been updated in some time due to efforts being focused on `tuya-convert` and `tuyapi`.

If you still have questions please feel free.
